name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Backend Docker images
      - name: Build Backend Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:api-gateway -f ./Back_End/API_Gateway/Dockerfile ./Back_End/API_Gateway
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:user-service -f ./Back_End/User-Management_Service/Dockerfile ./Back_End/User-Management_Service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:notification -f ./Back_End/User-Notification_Service/Dockerfile ./Back_End/User-Notification_Service

      # Step 5: Push Backend Docker images
      - name: Push Backend Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:notification

  # # Frontend Workflow
  # frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Step 1: Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v4  

  #     # Step 2: Set up Docker Buildx
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3 

  #     # Step 3: Log in to Docker Hub
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     # Step 4: Build Frontend Docker image
  #     - name: Build Frontend Docker image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/crud-micro:web -f ./Front_End/Dockerfile ./Front_End

  #     # Step 5: Push Frontend Docker image
  #     - name: Push Frontend Docker image
  #       run: |
  #         docker push ${{ secrets.DOCKER_USERNAME }}/crud-micro:web

